package med.app.Model;
// Generated 22 mars 2017 01:15:28 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Endorse generated by hbm2java
 */
@Entity
@Table(name = "endorse", catalog = "e_med")
public class Endorse implements java.io.Serializable {

	private Integer id;
	private Docteurs docteurs;
	private Patients patients;
	private int note;

	public Endorse() {
	}

	public Endorse(Docteurs docteurs, Patients patients, int note) {
		this.docteurs = docteurs;
		this.patients = patients;
		this.note = note;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_doc", nullable = false)
	public Docteurs getDocteurs() {
		return this.docteurs;
	}

	public void setDocteurs(Docteurs docteurs) {
		this.docteurs = docteurs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_patient", nullable = false)
	public Patients getPatients() {
		return this.patients;
	}

	public void setPatients(Patients patients) {
		this.patients = patients;
	}

	@Column(name = "note", nullable = false)
	public int getNote() {
		return this.note;
	}

	public void setNote(int note) {
		this.note = note;
	}

}
