package med.app.Model;
// Generated 22 mars 2017 01:15:28 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MessagesId generated by hbm2java
 */
@Embeddable
public class MessagesId implements java.io.Serializable {

	private int idMes;
	private String titreMes;
	private String contenuMes;
	private int idPatMes;
	private int idDocMes;
	private Date dateMes;

	public MessagesId() {
	}

	public MessagesId(int idMes, String titreMes, String contenuMes, int idPatMes, int idDocMes, Date dateMes) {
		this.idMes = idMes;
		this.titreMes = titreMes;
		this.contenuMes = contenuMes;
		this.idPatMes = idPatMes;
		this.idDocMes = idDocMes;
		this.dateMes = dateMes;
	}

	@Column(name = "id_mes", nullable = false)
	public int getIdMes() {
		return this.idMes;
	}

	public void setIdMes(int idMes) {
		this.idMes = idMes;
	}

	@Column(name = "titre_mes", nullable = false, length = 30)
	public String getTitreMes() {
		return this.titreMes;
	}

	public void setTitreMes(String titreMes) {
		this.titreMes = titreMes;
	}

	@Column(name = "contenu_mes", nullable = false, length = 400)
	public String getContenuMes() {
		return this.contenuMes;
	}

	public void setContenuMes(String contenuMes) {
		this.contenuMes = contenuMes;
	}

	@Column(name = "id_pat_mes", nullable = false)
	public int getIdPatMes() {
		return this.idPatMes;
	}

	public void setIdPatMes(int idPatMes) {
		this.idPatMes = idPatMes;
	}

	@Column(name = "id_doc_mes", nullable = false)
	public int getIdDocMes() {
		return this.idDocMes;
	}

	public void setIdDocMes(int idDocMes) {
		this.idDocMes = idDocMes;
	}

	@Column(name = "date_mes", nullable = false, length = 10)
	public Date getDateMes() {
		return this.dateMes;
	}

	public void setDateMes(Date dateMes) {
		this.dateMes = dateMes;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MessagesId))
			return false;
		MessagesId castOther = (MessagesId) other;

		return (this.getIdMes() == castOther.getIdMes())
				&& ((this.getTitreMes() == castOther.getTitreMes()) || (this.getTitreMes() != null
						&& castOther.getTitreMes() != null && this.getTitreMes().equals(castOther.getTitreMes())))
				&& ((this.getContenuMes() == castOther.getContenuMes()) || (this.getContenuMes() != null
						&& castOther.getContenuMes() != null && this.getContenuMes().equals(castOther.getContenuMes())))
				&& (this.getIdPatMes() == castOther.getIdPatMes()) && (this.getIdDocMes() == castOther.getIdDocMes())
				&& ((this.getDateMes() == castOther.getDateMes()) || (this.getDateMes() != null
						&& castOther.getDateMes() != null && this.getDateMes().equals(castOther.getDateMes())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdMes();
		result = 37 * result + (getTitreMes() == null ? 0 : this.getTitreMes().hashCode());
		result = 37 * result + (getContenuMes() == null ? 0 : this.getContenuMes().hashCode());
		result = 37 * result + this.getIdPatMes();
		result = 37 * result + this.getIdDocMes();
		result = 37 * result + (getDateMes() == null ? 0 : this.getDateMes().hashCode());
		return result;
	}

}
