package med.app.Model;
// Generated 22 mars 2017 01:15:28 by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Patients generated by hbm2java
 */
@Entity
@Table(name = "patients", catalog = "e_med")
public class Patients implements java.io.Serializable {

	private Integer idPatient;
	private Docteurs docteurs;
	private String nomPatient;
	private String prenomPatient;
	private String sexePatient;
	private int agePatient;
	private String etatCivilPatient;
	private Set<Messages> messageses = new HashSet<Messages>(0);
	private Set<RendezVous> rendezVouses = new HashSet<RendezVous>(0);
	private Set<Medicament> medicaments = new HashSet<Medicament>(0);
	private Set<Endorse> endorses = new HashSet<Endorse>(0);
	private Set<Symptomes> symptomeses = new HashSet<Symptomes>(0);

	public Patients() {
	}

	public Patients(Docteurs docteurs, String nomPatient, String prenomPatient, String sexePatient, int agePatient,
			String etatCivilPatient) {
		this.docteurs = docteurs;
		this.nomPatient = nomPatient;
		this.prenomPatient = prenomPatient;
		this.sexePatient = sexePatient;
		this.agePatient = agePatient;
		this.etatCivilPatient = etatCivilPatient;
	}

	public Patients(Docteurs docteurs, String nomPatient, String prenomPatient, String sexePatient, int agePatient,
			String etatCivilPatient, Set<Messages> messageses, Set<RendezVous> rendezVouses,
			Set<Medicament> medicaments, Set<Endorse> endorses, Set<Symptomes> symptomeses) {
		this.docteurs = docteurs;
		this.nomPatient = nomPatient;
		this.prenomPatient = prenomPatient;
		this.sexePatient = sexePatient;
		this.agePatient = agePatient;
		this.etatCivilPatient = etatCivilPatient;
		this.messageses = messageses;
		this.rendezVouses = rendezVouses;
		this.medicaments = medicaments;
		this.endorses = endorses;
		this.symptomeses = symptomeses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_patient", unique = true, nullable = false)
	public Integer getIdPatient() {
		return this.idPatient;
	}

	public void setIdPatient(Integer idPatient) {
		this.idPatient = idPatient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_doc", nullable = false)
	public Docteurs getDocteurs() {
		return this.docteurs;
	}

	public void setDocteurs(Docteurs docteurs) {
		this.docteurs = docteurs;
	}

	@Column(name = "nom_patient", nullable = false, length = 30)
	public String getNomPatient() {
		return this.nomPatient;
	}

	public void setNomPatient(String nomPatient) {
		this.nomPatient = nomPatient;
	}

	@Column(name = "prenom_patient", nullable = false, length = 30)
	public String getPrenomPatient() {
		return this.prenomPatient;
	}

	public void setPrenomPatient(String prenomPatient) {
		this.prenomPatient = prenomPatient;
	}

	@Column(name = "sexe_patient", nullable = false, length = 9)
	public String getSexePatient() {
		return this.sexePatient;
	}

	public void setSexePatient(String sexePatient) {
		this.sexePatient = sexePatient;
	}

	@Column(name = "age_patient", nullable = false)
	public int getAgePatient() {
		return this.agePatient;
	}

	public void setAgePatient(int agePatient) {
		this.agePatient = agePatient;
	}

	@Column(name = "etat_civil_patient", nullable = false, length = 12)
	public String getEtatCivilPatient() {
		return this.etatCivilPatient;
	}

	public void setEtatCivilPatient(String etatCivilPatient) {
		this.etatCivilPatient = etatCivilPatient;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patients")
	public Set<Messages> getMessageses() {
		return this.messageses;
	}

	public void setMessageses(Set<Messages> messageses) {
		this.messageses = messageses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patients")
	public Set<RendezVous> getRendezVouses() {
		return this.rendezVouses;
	}

	public void setRendezVouses(Set<RendezVous> rendezVouses) {
		this.rendezVouses = rendezVouses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patients")
	public Set<Medicament> getMedicaments() {
		return this.medicaments;
	}

	public void setMedicaments(Set<Medicament> medicaments) {
		this.medicaments = medicaments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patients")
	public Set<Endorse> getEndorses() {
		return this.endorses;
	}

	public void setEndorses(Set<Endorse> endorses) {
		this.endorses = endorses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patients")
	public Set<Symptomes> getSymptomeses() {
		return this.symptomeses;
	}

	public void setSymptomeses(Set<Symptomes> symptomeses) {
		this.symptomeses = symptomeses;
	}

}
