package med.app.Model;
// Generated 22 mars 2017 01:15:28 by Hibernate Tools 5.2.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Messages generated by hbm2java
 */
@Entity
@Table(name = "messages", catalog = "e_med")
public class Messages implements java.io.Serializable {

	private MessagesId id;
	private Docteurs docteurs;
	private Patients patients;

	public Messages() {
	}

	public Messages(MessagesId id, Docteurs docteurs, Patients patients) {
		this.id = id;
		this.docteurs = docteurs;
		this.patients = patients;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idMes", column = @Column(name = "id_mes", nullable = false)),
			@AttributeOverride(name = "titreMes", column = @Column(name = "titre_mes", nullable = false, length = 30)),
			@AttributeOverride(name = "contenuMes", column = @Column(name = "contenu_mes", nullable = false, length = 400)),
			@AttributeOverride(name = "idPatMes", column = @Column(name = "id_pat_mes", nullable = false)),
			@AttributeOverride(name = "idDocMes", column = @Column(name = "id_doc_mes", nullable = false)),
			@AttributeOverride(name = "dateMes", column = @Column(name = "date_mes", nullable = false, length = 10)) })
	public MessagesId getId() {
		return this.id;
	}

	public void setId(MessagesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_doc_mes", nullable = false, insertable = false, updatable = false)
	public Docteurs getDocteurs() {
		return this.docteurs;
	}

	public void setDocteurs(Docteurs docteurs) {
		this.docteurs = docteurs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pat_mes", nullable = false, insertable = false, updatable = false)
	public Patients getPatients() {
		return this.patients;
	}

	public void setPatients(Patients patients) {
		this.patients = patients;
	}

}
