package med.app.Model;
// Generated 22 mars 2017 01:15:28 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Symptomes generated by hbm2java
 */
@Entity
@Table(name = "symptomes", catalog = "e_med")
public class Symptomes implements java.io.Serializable {

	private Integer idSym;
	private Patients patients;
	private String intituleSym;
	private String descSym;

	public Symptomes() {
	}

	public Symptomes(Patients patients, String intituleSym, String descSym) {
		this.patients = patients;
		this.intituleSym = intituleSym;
		this.descSym = descSym;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_sym", unique = true, nullable = false)
	public Integer getIdSym() {
		return this.idSym;
	}

	public void setIdSym(Integer idSym) {
		this.idSym = idSym;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pat_sym", nullable = false)
	public Patients getPatients() {
		return this.patients;
	}

	public void setPatients(Patients patients) {
		this.patients = patients;
	}

	@Column(name = "intitule_sym", nullable = false, length = 30)
	public String getIntituleSym() {
		return this.intituleSym;
	}

	public void setIntituleSym(String intituleSym) {
		this.intituleSym = intituleSym;
	}

	@Column(name = "desc_sym", nullable = false, length = 100)
	public String getDescSym() {
		return this.descSym;
	}

	public void setDescSym(String descSym) {
		this.descSym = descSym;
	}

}
